import { PrismaClient, Paint } from "@prisma/client";
const prisma = new PrismaClient();

const paintSeedDatasource: Paint[] = [
  { id: -1, name: "Abaddon Black", hexColor: "#231F20" },
  { id: -1, name: "Averland Sunset", hexColor: "#FDB825" },
  { id: -1, name: "Balthasar Gold (Metal)", hexColor: "#A47552" },
  { id: -1, name: "Bugmans Glow", hexColor: "#834F44" },
  { id: -1, name: "Caledor Sky", hexColor: "#396E9E" },
  { id: -1, name: "Caliban Green", hexColor: "#00401F" },
  { id: -1, name: "Castellan Green", hexColor: "#314821" },
  { id: -1, name: "Celestra Grey", hexColor: "#90A8A8" },
  { id: -1, name: "Ceramite White", hexColor: "#FFFFFF" },
  { id: -1, name: "Daemonette Hide", hexColor: "#696684" },
  { id: -1, name: "Death Guard Green", hexColor: "#848A66" },
  { id: -1, name: "Deathworld Forest", hexColor: "#5C6730" },
  { id: -1, name: "Dryad Bark", hexColor: "#33312D" },
  { id: -1, name: "Incubi Darkness", hexColor: "#0B474A" },
  { id: -1, name: "Jokaero Orange", hexColor: "#EE3823" },
  { id: -1, name: "Kantor Blue", hexColor: "#002151" },
  { id: -1, name: "Khorne Red", hexColor: "#6A0001" },
  { id: -1, name: "Leadbelcher (Metal)", hexColor: "#888D8F" },
  { id: -1, name: "Macragge Blue", hexColor: "#0D407F" },
  { id: -1, name: "Mechanicus Standard Grey", hexColor: "#3D4B4D" },
  { id: -1, name: "Mephiston Red", hexColor: "#9A1115" },
  { id: -1, name: "Mournfang Brown", hexColor: "#640909" },
  { id: -1, name: "Naggaroth Night", hexColor: "#3D3354" },
  { id: -1, name: "Rakarth Flesh", hexColor: "#A29E91" },
  { id: -1, name: "Ratskin Flesh", hexColor: "#AD6B4C" },
  { id: -1, name: "Retributor Armour (Metal)", hexColor: "#C39E81" },
  { id: -1, name: "Rhinox Hide", hexColor: "#493435" },
  { id: -1, name: "Screamer Pink", hexColor: "#7C1645" },
  { id: -1, name: "Screaming Bell (Metal)", hexColor: "#C16F45" },
  { id: -1, name: "Steel Legion Drab", hexColor: "#5E5134" },
  { id: -1, name: "Stegadon Scale Green", hexColor: "#074863" },
  { id: -1, name: "The Fang Grey", hexColor: "#436174" },
  { id: -1, name: "Thousand Sons Blue", hexColor: "#18ABCC" },
  { id: -1, name: "Waaagh! Flesh", hexColor: "#1F5429" },
  { id: -1, name: "Warplock Bronze (Metal)", hexColor: "#927D7B" },
  { id: -1, name: "XV-88", hexColor: "#72491E" },
  { id: -1, name: "Zandri Dust", hexColor: "#9E915C" },
  { id: -1, name: "Administratum Grey", hexColor: "#949B95" },
  { id: -1, name: "Ahriman Blue", hexColor: "#1F8C9C" },
  { id: -1, name: "Alaitoc Blue", hexColor: "#295788" },
  { id: -1, name: "Altdorf Guard Blue", hexColor: "#1F56A7" },
  { id: -1, name: "Auric Armour Gold (Metal)", hexColor: "#E8BC6D" },
  { id: -1, name: "Balor Brown", hexColor: "#8B5910" },
  { id: -1, name: "Baneblade Brown", hexColor: "#937F6D" },
  { id: -1, name: "Bestigor Flesh", hexColor: "#D38A57" },
  { id: -1, name: "Brass Scorpion (Metal)", hexColor: "#B7885F" },
  { id: -1, name: "Cadian Fleshtone", hexColor: "#C77958" },
  { id: -1, name: "Calgar Blue", hexColor: "#4272B8" },
  { id: -1, name: "Dark Reaper", hexColor: "#3B5150" },
  { id: -1, name: "Dawnstone", hexColor: "#70756E" },
  { id: -1, name: "Deathclaw Brown", hexColor: "#B36853" },
  { id: -1, name: "Doombull Brown", hexColor: "#5D0009" },
  { id: -1, name: "Elysian Green", hexColor: "#748F39" },
  { id: -1, name: "Emperors Children", hexColor: "#B94278" },
  { id: -1, name: "Eshin Grey", hexColor: "#4A4F52" },
  { id: -1, name: "Evil Sunz Scarlet", hexColor: "#C2191F" },
  { id: -1, name: "Fenrisian Grey", hexColor: "#719BB7" },
  { id: -1, name: "Fire Dragon Bright", hexColor: "#F58652" },
  { id: -1, name: "Flash Gitz Yellow", hexColor: "#FFF200" },
  { id: -1, name: "Flayed One Flesh", hexColor: "#F0D9B8" },
  { id: -1, name: "Fulgurite Copper (Metal)", hexColor: "#FCFCDE" },
  { id: -1, name: "Gehenna's Gold (Metal)", hexColor: "#DBA674" },
  { id: -1, name: "Genestealer Purple", hexColor: "#7761AB" },
  { id: -1, name: "Gorthor Brown", hexColor: "#654741" },
  { id: -1, name: "Hashut Copper (Metal)", hexColor: "#B77647" },
  { id: -1, name: "Hoeth Blue", hexColor: "#4C7FB4" },
  { id: -1, name: "Ironbreaker (Metal)", hexColor: "#A1A6A9" },
  { id: -1, name: "Kabalite Green", hexColor: "#038C67" },
  { id: -1, name: "Karak Stone", hexColor: "#BB9662" },
  { id: -1, name: "Kislev Flesh", hexColor: "#D6A875" },
  { id: -1, name: "Liberator Gold (Metal)", hexColor: "#D3B587" },
  { id: -1, name: "Loren Forest", hexColor: "#50702D" },
  { id: -1, name: "Lothern Blue", hexColor: "#34A2CF" },
  { id: -1, name: "Moot Green", hexColor: "#52B244" },
  { id: -1, name: "Nurgling Green", hexColor: "#849C63" },
  { id: -1, name: "Ogryn Camo", hexColor: "#9DA94B" },
  { id: -1, name: "Pallid Wych Flesh", hexColor: "#CDCEBE" },
  { id: -1, name: "Pink Horror", hexColor: "#90305D" },
  { id: -1, name: "Runefang Steel (Metal)", hexColor: "#C3CACE" },
  { id: -1, name: "Runelord Brass (Metal)", hexColor: "#B6A89A" },
  { id: -1, name: "Russ Grey", hexColor: "#547588" },
  { id: -1, name: "Screaming Skull", hexColor: "#D2D4A2" },
  { id: -1, name: "Skarsnik Green", hexColor: "#5F9370" },
  { id: -1, name: "Skavenblight Dinge", hexColor: "#47413B" },
  { id: -1, name: "Skrag Brown", hexColor: "#90490F" },
  { id: -1, name: "Skullcrusher Brass (Metal)", hexColor: "#F1C78E" },
  { id: -1, name: "Slaanesh Grey", hexColor: "#8E8C97" },
  { id: -1, name: "Sotek Green", hexColor: "#0B6974" },
  { id: -1, name: "Squig Orange", hexColor: "#AA4F44" },
  { id: -1, name: "Stormhost Silver (Metal)", hexColor: "#BBC6C9" },
  { id: -1, name: "Stormvermin Fur", hexColor: "#736B65" },
  { id: -1, name: "Straken Green", hexColor: "#628126" },
  { id: -1, name: "Sybarite Green", hexColor: "#30A56C" },
  { id: -1, name: "Sycorax Bronze (Metal)", hexColor: "#CBB394" },
  { id: -1, name: "Tallarn Sand", hexColor: "#A67610" },
  { id: -1, name: "Tau Light Ochre", hexColor: "#BF6E1D" },
  { id: -1, name: "Teclis Blue", hexColor: "#317EC1" },
  { id: -1, name: "Temple Guard Blue", hexColor: "#339A8D" },
  { id: -1, name: "Thunderhawk Blue", hexColor: "#417074" },
  { id: -1, name: "Troll Slayer Orange", hexColor: "#F36D2D" },
  { id: -1, name: "Tuskgor Fur", hexColor: "#883636" },
  { id: -1, name: "Ulthuan Grey", hexColor: "#C7E0D9" },
  { id: -1, name: "Ungor Flesh", hexColor: "#D6A766" },
  { id: -1, name: "Ushabti Bone", hexColor: "#BBBB7F" },
  { id: -1, name: "Warboss Green", hexColor: "#3E805D" },
  { id: -1, name: "Warpfiend Grey", hexColor: "#6B6A74" },
  { id: -1, name: "Warpstone Glow", hexColor: "#1E7331" },
  { id: -1, name: "Wazdakka Red", hexColor: "#8C0A0C" },
  { id: -1, name: "White Scar", hexColor: "#FFFFFF" },
  { id: -1, name: "Wild Rider Red", hexColor: "#EA2F28" },
  { id: -1, name: "Xereus Purple", hexColor: "#471F5F" },
  { id: -1, name: "Yriel Yellow", hexColor: "#FFDA00" },
  { id: -1, name: "Zamesi Desert", hexColor: "#DDA026" },
  { id: -1, name: "Agrax Earthshade", hexColor: "#5A573F" },
  { id: -1, name: "Agrax Earthshade (Gloss)", hexColor: "#5A573F" },
  { id: -1, name: "Athonian Camoshade", hexColor: "#6D8E44" },
  { id: -1, name: "Biel-Tan Green", hexColor: "#1BA169" },
  { id: -1, name: "Carroburg Crimson", hexColor: "#A82A70" },
  { id: -1, name: "Casandora Yellow", hexColor: "#FECE5A" },
  { id: -1, name: "Coelia Greenshade", hexColor: "#0E7F78" },
  { id: -1, name: "Drakenhof Nightshade", hexColor: "#125899" },
  { id: -1, name: "Druchii Violet", hexColor: "#7A468C" },
  { id: -1, name: "Fuegan Orange", hexColor: "#C77E4D" },
  { id: -1, name: "Nuln Oil", hexColor: "#14100E" },
  { id: -1, name: "Nuln Oil (Gloss)", hexColor: "#14100E" },
  { id: -1, name: "Reikland Fleshshade", hexColor: "#CA6C4D" },
  { id: -1, name: "Reikland Fleshshade (Gloss)", hexColor: "#CA6C4D" },
  { id: -1, name: "Seraphim Sepia", hexColor: "#D7824B" },
  { id: -1, name: "Astorath Red", hexColor: "#DD482B" },
  { id: -1, name: "Changeling Pink", hexColor: "#F4AFCD" },
  { id: -1, name: "Chronus Blue", hexColor: "#72A8D1" },
  { id: -1, name: "Dawnstone", hexColor: "#919C9F" },
  { id: -1, name: "Eldar Flesh", hexColor: "#ECC083" },
  { id: -1, name: "Etherium Blue", hexColor: "#A2BAD2" },
  { id: -1, name: "Golden Griffon (Metal)", hexColor: "#A99058" },
  { id: -1, name: "Golgfag Brown", hexColor: "#C2804F" },
  { id: -1, name: "Hellion Green", hexColor: "#84C3AA" },
  { id: -1, name: "Hexos Palesun", hexColor: "#FFF200" },
  { id: -1, name: "Hoeth Blue", hexColor: "#57A9D4" },
  { id: -1, name: "Imrik Blue", hexColor: "#67AED0" },
  { id: -1, name: "Kindleflame", hexColor: "#F79E86" },
  { id: -1, name: "Longbeard Grey", hexColor: "#CECEAF" },
  { id: -1, name: "Lucius Lilac", hexColor: "#B69FCC" },
  { id: -1, name: "Necron Compound (Metal)", hexColor: "#828B8E" },
  { id: -1, name: "Niblet Green", hexColor: "#7DC734" },
  { id: -1, name: "Nurgling Green", hexColor: "#B8CC82" },
  { id: -1, name: "Praxeti White", hexColor: "#FFFFFF" },
  { id: -1, name: "Ryza Rust", hexColor: "#EC631A" },
  { id: -1, name: "Sigmarite", hexColor: "#CAAD76" },
  { id: -1, name: "Skink Blue", hexColor: "#58C1CD" },
  { id: -1, name: "Slaanesh Grey", hexColor: "#DBD5E6" },
  { id: -1, name: "Stormfang", hexColor: "#80A7C1" },
  { id: -1, name: "Sylvaneth Bark", hexColor: "#AC8262" },
  { id: -1, name: "Terminatus Stone", hexColor: "#BDB192" },
  { id: -1, name: "Thunderhawk Blue", hexColor: "#509BA9" },
  { id: -1, name: "Tyrant Skull", hexColor: "#CDC586" },
  { id: -1, name: "Underhive Ash", hexColor: "#C0BD81" },
  { id: -1, name: "Verminlord Hide", hexColor: "#A16954" },
  { id: -1, name: "Wrack White", hexColor: "#FCFBFA" },
  { id: -1, name: "Baharroth Blue", hexColor: "#58C1CD" },
  { id: -1, name: "Blue Horror", hexColor: "#A2BAD2" },
  { id: -1, name: "Dechala Lilac", hexColor: "#B69FCC" },
  { id: -1, name: "Dorn Yellow", hexColor: "#FFF200" },
  { id: -1, name: "Fulgrim Pink", hexColor: "#F4AFCD" },
  { id: -1, name: "Gauss Blaster Green", hexColor: "#84C3AA" },
  { id: -1, name: "Krieg Khaki", hexColor: "#C0BD81" },
  { id: -1, name: "Lugganath Orange", hexColor: "#F79E86" },
  { id: -1, name: "Bloodletter", hexColor: "#F37355" },
  { id: -1, name: "Guilliman Blue", hexColor: "#2F9AD6" },
  { id: -1, name: "Lamenters Yellow", hexColor: "#FFF56B" },
  { id: -1, name: "Waywatcher Green", hexColor: "#6DC066" },
  { id: -1, name: "Agrellan Badland", hexColor: "#ffb347" },
  { id: -1, name: "Agrellan Earth", hexColor: "#a17c59" },
  { id: -1, name: "Armageddon Dust", hexColor: "#D3A907" },
  { id: -1, name: "Armageddon Dunes", hexColor: "#926a25" },
  { id: -1, name: "Astrogranite", hexColor: "#757679" },
  { id: -1, name: "Astrogranite Debris", hexColor: "#3b424c" },
  { id: -1, name: "Blackfire Earth", hexColor: "#A75820" },
  { id: -1, name: "Lustrian Undergrowth", hexColor: "#415A09" },
  { id: -1, name: "Martian Ironcrust", hexColor: "#b7410e" },
  { id: -1, name: "Martian Ironearth", hexColor: "#c15a4b" },
  { id: -1, name: "Mourn Mountain Snow", hexColor: "#E9EAEB" },
  { id: -1, name: "Stirland Battlemire", hexColor: "#ae5a2c" },
  { id: -1, name: "Stirland Mud", hexColor: "#492B00" },
  { id: -1, name: "Valhallan Blizzard", hexColor: "#f2ede7" },
  { id: -1, name: "'Ardcoat", hexColor: "#E2DEDF" },
  { id: -1, name: "Agrellan Earth", hexColor: "#9A816B" },
  { id: -1, name: "Blood for the Blood God", hexColor: "#67080B" },
  { id: -1, name: "Imperial Primer", hexColor: "#231F20" },
  { id: -1, name: "Lahmian Medium", hexColor: "#F5EDE2" },
  { id: -1, name: "Liquid Green Stuff", hexColor: "#3B7A5F" },
  { id: -1, name: "Martian Ironearth", hexColor: "#C15A4B" },
  { id: -1, name: "Nihilakh Oxide", hexColor: "#6CB79E" },
  { id: -1, name: "Nurgle's Rot", hexColor: "#9B8F22" },
  { id: -1, name: "Soulstone Blue", hexColor: "#004EFA" },
  { id: -1, name: "Spiritstone Red", hexColor: "#FF4B24" },
  { id: -1, name: "Typhus Corrosion", hexColor: "#463D2B" },
  { id: -1, name: "Waystone Green", hexColor: "#00C000" },
];

export default async function seedPaints() {
  for (const seedPaint of paintSeedDatasource) {
    try {
      const newPaint = await prisma.paint.upsert({
        where: { name: seedPaint.name },
        update: {
          name: seedPaint.name,
          hexColor: seedPaint.hexColor.replace("#", ""),
        },
        create: {
          name: seedPaint.name,
          hexColor: seedPaint.hexColor.replace("#", ""),
        },
      });
    } catch (err) {
      console.log(`Error while seeding Paint: ${err}`);
    }
  }
}
